
---
- include_vars:     secrets.yml

- name:             install yum dependencies
  yum:              name={{ item }} state=present
  with_items:       '{{ wordpress_dependencies.yum }}'

- name:             install pip dependencies
  pip:              name={{ item }} state=present
  with_items:       '{{ wordpress_dependencies.pip }}'

- name:             download wordpress
  get_url:          url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name:             extract archive
  command:          chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress

- name:             add group "wordpress"
  group:            name=wordpress

- name:             add user "wordpress"
  user:             name=wordpress group=wordpress home=/srv/wordpress/

- name:             Fetch random salts for WordPress config
  command:          curl https://api.wordpress.org/secret-key/1.1/salt/
  register:         "wp_salt"

- name:             create wordpress database
  mysql_db:
    name:           '{{ wp_db_name }}'
    state:          present
    login_user:     root
    login_password: '{{ mysql_root_password }}'
    login_host:     '{{ docker_mysql_ip }}'
  notify:
  - restart php-fpm
  - initialize wordpress
  - download weather information
  - create wordpress weather post file
  - create wordpress weather post

- name:             create wordpress database user
  mysql_user:
    name:           '{{ wp_db_user }}'
    password:       '{{ wp_db_password }}'
    priv:           '{{ wp_db_name }}.*:ALL'
    state:          present
    login_user:     root
    host:           '{{ docker_gateway_ip }}'
    login_password: '{{ mysql_root_password }}'
    login_host:     '{{ docker_mysql_ip }}'
  notify:           restart php-fpm

- name:             copy wordpress config file
  template:         src=wp-config.php dest=/srv/wordpress/
  notify:           restart php-fpm

- name:             copy php-fpm.d/www.conf config file
  template:         src=www.conf dest=/etc/php-fpm.d/
  notify:           restart php-fpm

- name:             change ownership of wordpress installation
  file:             path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes setype=httpd_sys_content_t
  notify:           restart php-fpm

- name:             download wp-cli
  get_url:
    url:            https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest:           /bin/wp
    mode:           0775
