---
- name:    restart php-fpm
  service: name=php-fpm state=restarted

- name:    initialize wordpress
  shell:   wp core install --path=/srv/wordpress/ --url='{{ wp_home }}' --title="{{ wp_title }}" --admin_user=admin --admin_password='{{ wp_admin_pass }}' --admin_email='{{ wp_admin_email }}'

- name: download weather information
  uri:
    url: https://www.metaweather.com/api/location/{{ metaweather_woeid }}/
    return_content: yes
  register: metaweather_data

- name: create wordpress weather post file
  template: src=weather-post.txt dest=/srv/wordpress

- name: create wordpress weather post
  shell: wp post create /srv/wordpress/weather-post.txt --post_title='Weather Post!' --path=/srv/wordpress --post_status=publish
